plugins {
    id 'net.minecraftforge.gradle'
    id 'maven-publish'
}

version = project.property('mod_version')
group = project.property('maven_group')

base {
    archivesName = "${project.property('archives_base_name')}-forge"
}

minecraft {
    mappings channel: 'official', version: project.property('minecraft_version')

    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            mods {
                chunkis {
                    source sourceSets.main
                }
            }
        }
        server {
            workingDirectory project.file('run/server')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            mods {
                chunkis {
                    source sourceSets.main
                }
            }
        }
    }
}

jarJar.enable()

repositories {
    mavenCentral()
    maven {
        name = 'MinecraftForge'
        url = 'https://maven.minecraftforge.net/'
    }
}

dependencies {
    minecraft "net.minecraftforge:forge:${project.property('forge_version')}"

    implementation 'io.liparakis.chunkis:chunkis-core:2.1.0'
    jarJar 'io.liparakis.chunkis:chunkis-core:[2.1.0,)'
}

tasks.withType(JavaCompile).configureEach {
    options.release = 21
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
    withSourcesJar()
}

jar {
    manifest {
        attributes([
            'Specification-Title'     : 'chunkis',
            'Specification-Vendor'    : 'Liparakis',
            'Specification-Version'   : '1',
            'Implementation-Title'    : project.name,
            'Implementation-Version'  : project.version,
            'Implementation-Vendor'   : 'Liparakis',
        ])
    }
    finalizedBy('reobfJar')
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact jar
        }
    }
}
