pluginManagement {
    repositories {
        maven {
            name = 'MinecraftForge'
            url = 'https://maven.minecraftforge.net/'
        }
        gradlePluginPortal()
    }
    plugins {
        id 'net.minecraftforge.gradle' version '6.+'
    }
}

rootProject.name = 'chunkis-forge'

// Include core locally so Gradle substitutes the dependency automatically.
includeBuild '../core'
